### ISSUE TITLE
Detailed howto

### ISSUE THREAD

**Issue by ArchGalileu** [mrmurilo75/pretix-sibs-payment-gateway-plugin#1]
Congrats for the plugin, i want and need it ;)

Can i use with main pretix website?

Or i have to be self-hosted? If so, can i use in production?

Any advices?

Best regards
ArchGalileu

PS. It is for my concerts of classical music here in Portugal, and it is so difficult to make it happen... Anyway thanks in advance ;)

**Comment by mrmurilo75** [comment]
The plugin is only in the beginning of the development. But we'll reply back to let you know when it is ready for production.
The documentation for plugin development doesnt mention the need for self-hosting, so I believe that you should be able to request the plugin. However, we the plugin is not yet in the plugin marketplace (due to the early development stage, but it should be there when ready).

**Comment by ArchGalileu** [comment]
Thank you very much ;)

I wait with pacience :)

Best regards
